"""add user, glucose_reading, medication, doctor_visit, general_note tables

Revision ID: 96c43b5f66d9
Revises: 8e0e1bb1e797
Create Date: 2026-07-22 17:58:21.846267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c43b5f66d9'
down_revision: Union[str, Sequence[str], None] = '8e0e1bb1e797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('diabetes_type', sa.Enum('TYPE_1', 'TYPE_2', 'GESTATIONAL', 'PREDIABETES', 'OTHER', name='diabetestypeenum'), nullable=False),
    sa.Column('target_range_low', sa.Float(), nullable=False),
    sa.Column('target_range_high', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('doctor_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_visits_id'), 'doctor_visits', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_visits_user_id'), 'doctor_visits', ['user_id'], unique=False)
    op.create_table('general_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_notes_id'), 'general_notes', ['id'], unique=False)
    op.create_index(op.f('ix_general_notes_user_id'), 'general_notes', ['user_id'], unique=False)
    op.create_table('glucose_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('context', sa.Enum('FASTING', 'BEFORE_MEAL', 'AFTER_MEAL', 'BEDTIME', 'RANDOM', 'OTHER', name='readingcontextenum'), nullable=True),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glucose_readings_id'), 'glucose_readings', ['id'], unique=False)
    op.create_index(op.f('ix_glucose_readings_user_id'), 'glucose_readings', ['user_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribing_doctor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_index(op.f('ix_medications_user_id'), 'medications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_user_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_glucose_readings_user_id'), table_name='glucose_readings')
    op.drop_index(op.f('ix_glucose_readings_id'), table_name='glucose_readings')
    op.drop_table('glucose_readings')
    op.drop_index(op.f('ix_general_notes_user_id'), table_name='general_notes')
    op.drop_index(op.f('ix_general_notes_id'), table_name='general_notes')
    op.drop_table('general_notes')
    op.drop_index(op.f('ix_doctor_visits_user_id'), table_name='doctor_visits')
    op.drop_index(op.f('ix_doctor_visits_id'), table_name='doctor_visits')
    op.drop_table('doctor_visits')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
